### ISSUE TITLE
Support newer terraform versions

### ISSUE THREAD

**Issue by errm** [cookpad/terraform-aws-eks#215] opened 2021-06-03 12:07 UTC
We should add support for the latest terraform (currently 0.15.5)

We need to check if users are still depending on other versions - we might need to test against multiple versions - or require an upgrade 🤷‍♂️

**Comment by ettiee** [comment] 2021-11-19 10:03
Duplicate of #267 ?

**Comment by aidy** [comment] 2022-02-22 10:29
Closing in favour of #267

**Closed by aidy** 2022-02-22 10:29 UTC
